workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    # integrations:
    #   app_store_connect: codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Замените на ваши данные
        BUNDLE_ID: "com.yourname.pomodorotimer"
        APP_NAME: "Pomodoro Timer"
      groups:
        - appstore_credentials
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: develop
          include: true
          source: true
     scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS (unsigned) and always produce IPA
        script: |
          set -euxo pipefail

          # 1) Пытаемся сделать готовый .ipa штатной командой
          if flutter build ipa --release --no-codesign; then
            echo "Flutter produced IPA successfully."
            IPA_DIR="build/ios/ipa"
            if ls "$IPA_DIR"/*.ipa >/dev/null 2>&1; then
              echo "Found IPA(s) in $IPA_DIR"
              exit 0
            fi
          fi

          echo "Fallback: build .app and package into unsigned .ipa manually"

          # 2) Делаем .app без подписи
          flutter build ios --release --no-codesign

          # 3) Ищем собранный .app (обычно Runner.app)
          APP_PATH=$(find build/ios/iphoneos -maxdepth 2 -type d -name "*.app" | head -n1)
          if [ -z "$APP_PATH" ]; then
            echo "ERROR: .app was not produced"; exit 1
          fi
          echo "Found app: $APP_PATH"

          # 4) Пакуем вручную в IPA: Payload/Runner.app -> Runner-unsigned.ipa
          WORKDIR="build/ios/ipa"
          mkdir -p "$WORKDIR/Payload"
          # Чистим старые
          rm -rf "$WORKDIR/Payload/"*.app || true
          rm -f "$WORKDIR"/*.ipa || true

          cp -R "$APP_PATH" "$WORKDIR/Payload/"

          pushd "$WORKDIR" >/dev/null
          # zip без доп. атрибутов; формат .ipa — это обычный zip
          /usr/bin/zip -qry Runner-unsigned.ipa Payload
          popd >/dev/null

          echo "Unsigned IPA at: $WORKDIR/Runner-unsigned.ipa"
          ls -la "$WORKDIR"

      - name: List outputs (diagnostic)
        script: |
          set -eux
          ls -la build || true
          ls -la build/ios || true
          ls -la build/ios/ipa || true
          find build -type f -name '*.ipa' -print || true
          find build -type d -name '*.app' -print || true
     artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  ios-release-workflow:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    # integrations:
    #   app_store_connect: codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.yourname.pomodorotimer"
        APP_NAME: "Pomodoro Timer"
      groups:
        - appstore_credentials
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: v*.*.*
          include: true
    scripts:
      - name: Set up keychain
        script: |
          # initialize keychain (no App Store Connect integration required)
          keychain initialize || true
      # Skipping automatic fetch of signing files so build can run without App Store Connect
      - name: Prepare code signing (skipped automatic fetch)
        script: |
          echo "Skipping app-store-connect signing fetch. Ensure you have required signing files if you need a signed IPA."
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods (non-fatal)
        script: |
          # Install CocoaPods but don't fail the whole build on non-critical pod warnings/errors
          set -e
          find . -name "Podfile" -execdir pod install \; || echo "pod install exited with non-zero status but continuing"
      - name: Flutter build ipa (unsigned)
        script: |
          # Build unsigned IPA so Codemagic can produce an artifact without App Store Connect
          flutter build ipa --release --no-codesign || flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    # Publishing to App Store Connect is disabled in this config to avoid missing integration errors.