name: Build and Deploy Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Clone Flutter repository with stable channel
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        cache: true
    
    - name: Doctor
      run: flutter doctor -v
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Web
      run: flutter build web --release --base-href="/pomodoro/"
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web